---
# tasks file for install_httpd
- name: Install httpd
  yum:
    name: "{{ package_name }}"
    state: present
  become: yes


- name: Start httpd
  service:
    name: "{{ package_name }}"
    state: started
    enabled: yes
  become: yes

- name: Copy files
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: yes
